Bring forward SPS marketplace adjustments
unity-sds/unity-sps pull request #245
Opened 2024-12-09 07:23 UTC by jpl-btlunsfo

## Purpose

- Bring the extra bits SPS requires to safely install from the Unity Marketplace into the develop branch.

## Proposed Changes

- ADD some extra variables (unused) required by the management console's installation procedures
- CHANGE some of the module source references to work inside the management console (ssh vs https fetch issues)

## Issues

- unity-sds/unity-sps#59

## Testing

- Currently deployed in `unity-venue-dev` under `btl-df1`/`dev` (standard password)
  - http://btl-df1-dev-httpd-alb-1474979360.us-west-2.elb.amazonaws.com:8080/btl-df1/dev/sps/
  - https://www.dev.mdps.mcp.nasa.gov:4443/btl-df1/dev/sps/

2024-12-09 07:25 UTC, jpl-btlunsfo commented
Just to note, this PR is actually also including the changes from #228, as they're necessary for the installation's proxies (though #228's changes arent merged yet)

2024-12-09 07:27 UTC, jpl-btlunsfo commented on terraform-unity/modules/terraform-unity-sps-eks/main.tf
> +  source          = "git::https://github.com/unity-sds/unity-cs-infra.git//terraform-unity-eks_module?ref=59-sps-eks-marketplace-adjustments"
At present, this is pinned to a temporary tag (`59-sps-eks-marketplace-adjustments`), but I'm going to work with Galen on getting those changes into main, hopefully in the next day or two.

2024-12-09 16:54 UTC, LucaCinquini requested changes
Hi @jpl-btlunsfo : I was able to deploy from this branch and execute the DAGs successfully. Only question: what are the new parameters needed by the Management Console? In particular, can we set "deployment_name" to be the same as "project", so we don't have to define the same value twice for 2 different variables?

2024-12-09 17:05 UTC, jpl-btlunsfo commented
> what are the new parameters needed by the Management Console

The management console, when installing terraform modules/applications, does a really odd force-injection of variables [here](https://github.com/unity-sds/unity-management-console/blob/main/backend/internal/terraform/management.go#L194-L200). I _think_ the terraform call includes some 'strict' setting, as the absence of any of the variables included there in the actual terraform config throws a fatal error (in the management console output at least).

> can we set "deployment_name" to be the same as "project", so we don't have to define the same value twice for 2 different variables

`deployment_name` is never actually used by the SPS terraform configuration (nor are `tags` or `install_prefix`). It _does_ get injected by the management console though?

I guess we could set its default to something simple (like a `""` empty string or something), but it definitely needs to be its own separate variable, if only to keep the management console's installer code happy.

2024-12-09 17:18 UTC, LucaCinquini commented
@jpl-btlunsfo : ok, can you set the default value of "deployment_name" to be ""? Then we can merge these changes.

2024-12-09 18:17 UTC, jpl-btlunsfo commented on terraform-unity/modules/terraform-unity-sps-eks/main.tf
> +  source          = "git::https://github.com/unity-sds/unity-cs-infra.git//terraform-unity-eks_module?ref=59-sps-eks-marketplace-adjustments"
right, these changes have been merged (and `59-sps-eks-marketplace-adjustments` cleaned up/deleted). We'll need to ask CS for a new tag/make a new tag for ourselves to track on before I can fix/merge this PR for good, I think.

2024-12-09 19:19 UTC, jpl-btlunsfo commented on terraform-unity/modules/terraform-unity-sps-eks/main.tf
> +  source          = "git::https://github.com/unity-sds/unity-cs-infra.git//terraform-unity-eks_module?ref=59-sps-eks-marketplace-adjustments"
updated to new tag!

2024-12-09 19:27 UTC, jpl-btlunsfo commented
tag updated, just need an approval to merge (will hold merging until I run another test-deploy).

2024-12-09 19:45 UTC, LucaCinquini approved these changes
Thanks, approved.

2024-12-10 04:13 UTC, jpl-btlunsfo commented
No issues on personal deploy!

2024-12-10 04:13 UTC, merged